services:
  timemachine:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - timemachine-data:/app/instance

volumes:
  timemachine-data: